version: '3.4'
services:
  omada:
    image: mbentley/omada-controller:4.4
    container_name: omada-controller
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-work:/opt/tplink/EAPController/work
      - omada-logs:/opt/tplink/EAPController/logs
      - ./tls.crt:/cert/tls.crt
      - ./tls.key:/cert/tls.key
    restart: unless-stopped
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    network_mode: host
volumes:
  omada-data:
  omada-work:
  omada-logs:
